name: Cotik Order Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  monitor-orders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Restore notified orders cache
        uses: actions/cache@v3
        with:
          path: notified_orders.txt
          key: notified-orders
      - name: Run order check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COTIK_AL_TOKEN: ${{ secrets.COTIK_AL_TOKEN }}
        run: python check-and-notify.py
      - name: Upload response log
        uses: actions/upload-artifact@v4
        with:
          name: response-log
          path: response.log
      - name: Save updated notified orders cache
        uses: actions/cache@v3
        with:
          path: notified_orders.txt
          key: notified-orders-${{ github.run_id }}
          restore-keys: |
            notified-orders