name: Cotik Order Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  monitor-orders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Download previous artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: notified-orders
          path: .
          github_token: ${{ secrets.GH_PAT }}
          workflow_conclusion: success
          if_no_artifact_found: ignore
      - name: Show notified_orders.txt
        run: |
          echo "=== notified_orders.txt content ==="
          cat notified_orders.txt || echo "File not found"
      - name: Run order check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COTIK_AL_TOKEN: ${{ secrets.COTIK_AL_TOKEN }}
        run: python check-and-notify.py
      - name: Upload updated notified_orders.txt
        uses: actions/upload-artifact@v4
        with:
          name: notified-orders
          path: notified_orders.txt