name: Cotik Order Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  monitor-orders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run order check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COTIK_AL_TOKEN: ${{ secrets.COTIK_AL_TOKEN }}
        run: python check-and-notify.py
      - name: Upload response log
        uses: actions/upload-artifact@v4
        with:
          name: response-log
          path: response.log
      - name: Debug whoami and token use
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "GH_PAT present: ${{ secrets.GH_PAT != '' }}"
      - name: Set remote with PAT
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
      - name: Commit and push updated notified_orders.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git pull
          git add notified_orders.txt
          git commit -m "Update notified orders list [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git